#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 8
install: 
  - npm install
#运行的脚本命令
script:
  - npm test
#上传覆盖率报告  
after_success: npm run coverage  
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master