export const PROXY_EVENT_KEY = '__EVENT__';
export const PROXY_EVENT_BEFORE_EXECUTE = '__EVENT__BEFORE__EXECUTE__';
export const PROXY_EVENT_AFTER_EXECUTE = '__EVENT__AFTER_EXECUTE__';
export const PROXY_LOOP_SPLIT = ',';